### ISSUE TITLE
Tracking issue for proc_macro conversion

### ISSUE THREAD

**Issue by jebrosen** [SergioBenitez/Rocket#693]
# Motivation

`rocket_codegen` currently uses Rust's `plugin` system, which is slated for future removal and is a leading cause of breakage on nightly Rust. Rocket should move to implementing its code generation through `proc_macro` and related features for better stability guarantees.

## Related issues

* SergioBenitez/Rocket#678: Stop using the quote_ macros. This conversion process supersedes that issue.
* rust-lang/rust#38356: `proc_macro` tracking issue
* rust-lang/rust#52121: merge several `proc_macro` features as `proc_macro_hygiene`

## Questions/Concerns

* Forward compatibility, including everything to do with possible changes to feature gates, hygiene, and editions.
* Hygiene

### Attribute macros:

* [x] `route` and its variants (`get`, `put`, `post`, `delete`, `head`, `patch`, `options`)
* [x] `catch`

### Custom derives:

* [x] `derive(FromForm)`
* [x] `derive(FromFormValue)`
* [x] `derive(Responder)`
* [x] `derive(UriDisplay)`

### Bang macros:

* [x] `routes!`: #680
* [x] `catchers!`: PR: #680
* [x] `uri!`
* [x] `rocket_internal_uri!` (some remaining work on the diagnostics)

### Upstream:

* [ ] https://github.com/rust-lang/rust/issues/43081

## Required rustc Features

These unstable features will need to be used by Rocket's proc_macro crate.

* `proc_macro_diagnostic`, `proc_macro_span`. Allows Rocket to provide useful error messages from macros.

These unstable features will need to be used by application crates that use Rocket's macros.
* `proc_macro_hygiene`. For macros that expand to non-items or macro definitions, including `routes!`, `catchers!`, and `uri!`, and `#[route]`.
* `decl_macro`, for `#[route]`.

## Testing

* All existing tests for attribute syntax, etc.
* Verify that macros work via all applicable import mechanisms: macro_use (`#[macro_use] extern crate rocket;`), use_extern_macros (`use rocket::macro`), and proc_macro_path_invoc (`#[derive(rocket::macro)],` `#[rocket::macro]`, or `rocket::macro!()`), and any others missing from this list. Ensure these cases are enough to cover compatibility with consumer crates that target the 2018 edition as well.

**Comment by SergioBenitez** [comment]
Note: https://github.com/rust-lang/rust/issues/43081#issuecomment-409078027 is still an issue, and will surely lead to confusion. Also, Rocket is _still_ using private APIs to work around not having an implementation for https://github.com/rust-lang/rust/pull/54373#issuecomment-423712817.
